In [1]:
import numpy as np

In [ ]:
class student:
    def __init__(self,name)->:
        self.name = name

In [5]:
lst=[1,2,3,4]
print(lst)
v = np.array([1,2,3,4])
print(v)
print("="*20)
m=np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
print(m.ndim)


[1, 2, 3, 4]
[1 2 3 4]
2


In [3]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape(2,3)
print(vec)
print(mat)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [7]:
def array_reshape(arr, rows =- 1, cols =- 1):
    try:
        arr = np.array(arr)
        return arr.reshape(rows, cols)
    except (TypeError, ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")

array_reshape([1,2,3,4,5,6,7,8,9],3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
def convert_dtype(arr,dtype):
    
    if not isinstance(arr,np.ndarray):
        
    arr = np.array(arr)
    
    

In [6]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.isclose(v1,v2,atol=3)

array([ True,  True,  True])

In [8]:
lst=[1,2,3,4,5,6]
lst = np.array(lst)
print(lst)
zeros = np.zeros((2,3))
print(zeros)
ones = np.ones((2,3))
print(ones)

[1 2 3 4 5 6]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
range_array = np.arange(0,9)
print(range_array)
array_2= range_array.reshape(3,3)
print(array_2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
range_array = np.arange(0,9,2)
print(range_array)

[0 2 4 6 8]


In [16]:
line_space = np.linspace(0,10,5)
print(line_space)

[ 0.   2.5  5.   7.5 10. ]


In [17]:
array_2 = np.random.randint(10,50,(3,2))
print(array_2)

[[24 27]
 [14 38]
 [41 43]]


In [21]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.dtype)

(2, 3)
int64


In [25]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[-1])

1
6


In [29]:
arr = np.array([1,2,3,4,5,6])
print(arr[0:2])
print(arr[-1:-5:-1])

[1 2]
[6 5 4 3]


In [36]:
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr[0,1])
print(arr[1,2])

2
6


In [38]:
arr = np.array([[1,2,3],
               [4,5,6]])
print(arr[0:1,1:2])
print(arr[1:,2:])

[[2]]
[[6]]
