In [2]:
import numpy as np

task_1

In [8]:
def array_factory(mode:str, shape : tuple, value:int=None):
    """
    Creates various NumPy arrays based on the mode.
    - 'zeros': Array filled with 0.
    - 'ones': Array filled with 1.
    - 'full': Array filled with a specified 'value'.
    - 'identity': A square identity matrix of size 'shape'.
    """
    if mode not in ["zeros","ones","full","identity"]:
        raise ValueError("invalid mode")
    else:
        
        if mode == 'zeros' :
            zeros = np.zeros(shape)
            return zeros
        elif mode == 'ones':
            ones = np.ones(shape) 
            return ones
        elif mode == 'full':
            full = np.full((shape),value)
            return full
        else:
            if shape[0] == shape[1]:
                identity = np.eye(shape[0])
                return identity
            else:
                raise ValueError("the identity matrix should rows = columns ")


the_mode = input("inter mode : ").lower()
the_shape= tuple( map(int,input("inter shape : ").split(",")) )
if the_mode == 'full': 
    the_value = int(input("inter value : "))
else:
     the_value = None

the_result = array_factory(the_mode,the_shape,the_value)
print(the_result)


    

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


task-2

In [9]:
def secure_reshape_and_stack(data1:list, data2:list, new_shape:tuple):
    """
    1. Validates and converts inputs to NumPy arrays.
    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        # Convert inputs to ndarray to ensure they are processed as Tensors 
        # arr = np.array(data1)

        arr1 = np.array(data1)
        arr2 = np.array(data2).reshape(1,-1)

        # Rule: Change the shape of arr1 to new_shape 
        # Common usage: turning a vector (1D) into a matrix (2D)  by using reshape function 
        reshaped_arr1 = arr1.reshape(new_shape)

        # Rule: Vertical Stacking (vstack) 
        # Requirement: Both matrices must have the same number of columns
        combined_dataset = np.vstack((arr2,reshaped_arr1))
        
        return combined_dataset

    except ValueError as e:
        # Handle cases where reshape size doesn't match or stack columns don't match
        raise ValueError(f"Company-grade Error: {e}")


data1 = list(map(int,input("inter your data1: ").split(",")))
data2 = list(map(int,input("inter your data2: ").split(",")))
new_shape = tuple(map(int,input("inter your shape: ").split(",")))
result = secure_reshape_and_stack(data1,data2,new_shape)
print(result)

[[1 2 3]
 [1 2 3]]


task_3

In [10]:
def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Finds elements satisfying a condition (>= threshold) 
    and replaces them with a new value.
    """
    # 1. Convert input to a numpy array (ndarray)
    arr =np.array(arr)
    # 2. Define the condition: elementwise comparison 
    # This creates a Boolean numpy array 
    condition = arr >= threshold
    
    # 3. Apply Modification using np.where() 
    # np.where(condition, value_if_true, value_if_false)
    modified_arr =np.where(condition,replacement_value,arr)
    
    return modified_arr

In [11]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])